### ISSUE TITLE
в задаче на входе две строки, а обрабатывается одна

### ISSUE THREAD

**Issue by StanislavVolodarskiy** [ByMyKolaps/Task6_Tinkoff#1]
В задаче в первой строке одно число. Вы обрабатываете его в цикле как массив из одного элемента.

**Comment by ByMyKolaps** [comment]
Это было сделано для удобства тестирования, чтобы в цикле while(true) в Main-е, при вводе массива, не нужно было каждый раз указывать его длину. В любом случае, исправил, но проблему это не решило.

**Comment by StanislavVolodarskiy** [comment]
Не работает. Печатает ответ, падает с исключением.
```
$ echo -e "4\n4 3 2 1" | mono Temp.exe
-1 -1

Unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: s
  at System.Int32.Parse (System.String s) [0x00003] in <de882a77e7c14f8ba5d298093dde82b2>:0 
  at Task6.Program.Main (System.String[] args) [0x00009] in <73d0fa7e55794508aa4894f74100fd1c>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
Parameter name: s
  at System.Int32.Parse (System.String s) [0x00003] in <de882a77e7c14f8ba5d298093dde82b2>:0 
  at Task6.Program.Main (System.String[] args) [0x00009] in <73d0fa7e55794508aa4894f74100fd1c>:0 
```

**Comment by ByMyKolaps** [comment]
Исправлено

**Comment by StanislavVolodarskiy** [comment]
> Исправлено

Заработало? Контест принимает это решение?

**Comment by ByMyKolaps** [comment]
Нет, так и не заработало. У Вас возникло исключение, т.к ввод данных (n и сам массив) у меня находились в вечном цикле, чтобы каждый раз не нужно было перекомпилировать программу для тестирования новых данных. При отправке кода в систему, я убирал этот вечный цикл и добавлял:
var n = int.Parse(Console.ReadLine()).
Сейчас я это исправил и код в репозитории теперь полностью соответствует коду, который я отправляю в проверяющую систему. Но текущее решение все так же не проходит все тесты.
